Repository SimonCastonguayETS/oxygencs-grp1-eq12, pull requests merged in 2024-03, with the labels that each got.

#9 connexion db et envoit des données et évenements
  src/main.py
Labels: Fonctionnalité

#8 connection avec HVAC web
  .gitignore
  Pipfile
  Pipfile.lock
  src/main.py
Labels: Fonctionnalité

#11 ajout du fichier de configuration des env
  config.env
  requirements.txt
  src/main.py
Labels: Fonctionnalité

#14 Test unitaire
  Pipfile
  requirements.txt
  src/main.py
  test/test.py
Labels: Fonctionnalité

#16 readme
  README.md
Labels: Documentation

#17 adding Docker image for the python project
  .dockerignore
  Dockerfile
  requirementsDocker.txt
  src/main.py
Labels: Fonctionnalité

#21 Ajouter CI
  .github/workflows/docker-image.yml
  requirements.txt
  src/main.py
Labels: Fonctionnalité, Amélioration

#19 Ajouter un pre-commit hook
  .pre-commit-config.yaml
  README.md
  requirements.txt
Labels: Fonctionnalité, Amélioration

#20 added the info in the readme
  README.md
Labels: Documentation
